### ISSUE TITLE
error in of_v0.11.0 macOS/Windows

### ISSUE THREAD

**Issue by moebiussurfing** [galsasson/ofxInterface#9]
@galsasson , @armadillu, 
any chance to solve this?
It happens in OF GitHub branch since  commits from 3 weeks ago

> /of_v0.11.0_osx_release/addons/ofxInterface/src/Node.cpp:463:65: No member named 'getInverse' in 'glm::mat<4, 4, float, glm::packed_highp>'

```
//Node.cpp
ofVec3f Node::toLocal(const ofVec3f &screenPoint)
{
	#ifdef GLM_SWIZZLE //this version of OF is using GLM for math ops
	return (ofVec3f)screenPoint * glm::inverse(ofNode::getGlobalTransformMatrix());
	#else
	return (ofVec3f)screenPoint*ofNode::getGlobalTransformMatrix().getInverse();
	#endif
}
```

NOTE:
Editing this on OF core, do not seems to help...
```
//ofConstants.h
// Set to 1 for compatibility with old projects using ofVec instead of glm
#ifndef OF_USE_LEGACY_VECTOR_MATH
	#define OF_USE_LEGACY_VECTOR_MATH 1
#endif
```

**Comment by eduardfrigola** [comment]
It seems to be the way it's check if the project is using GLM or not, it uses the getInverse method which is not implemented in for glm matrix. Swizzle was disabled some time ago to speed up things: https://github.com/openframeworks/openFrameworks/commit/a5e069585621289022049a9aa79ab4da2e497c01.

Maybe change the way checking if is using GLM with OF_USE_LEGACY_VECTOR_MATH?

**Comment by armadillu** [comment]
I haven't been keeping up with newer OF releases; but I know it can be hard to keep compatibility as these macros come and go without a clear way to discern exact commits. So the only solution may be having a branch for older compatibility, and keeping master up to date with OF master

**Comment by moebiussurfing** [comment]
thanks @eduardfrigola ,
I just disabled the ofVec3f checking to work with current OF (github master glm mode) and it works again:
```
//Node.cpp
ofVec3f Node::toLocal(const ofVec3f &screenPoint)
{
	//#ifdef GLM_SWIZZLE //this version of OF is using GLM for math ops
	return (ofVec3f)screenPoint * glm::inverse(ofNode::getGlobalTransformMatrix());
	//#else
	//return (ofVec3f)screenPoint*ofNode::getGlobalTransformMatrix().getInverse();
	//#endif
}
```
